experiments:

  s_eff:
    pop_size: [5000]
    mut_rate: [0.006]
    s_normal: [0.004, 0.001, 0.0004]
    s_range: [0.2]
  
  U_eff:
    pop_size: [5000]
    mut_rate_normal: [0.012, 0.006, 0.003]
    mut_rate_range: [0.2]
    sel_coef: [0.001]

constants:
  CHRMLEN: 15000
  BURNIN: 5000
  N_SIM: 2000
  N_SAM: 1000
  ESTIMATE_N_SIM: 200
  N_SIGMA: 1
  SIGMA_RANGE: [0.0, 0.25]
  N_SEL_COEF: 1
