experiments:

  s_eff:
    pop_size: [5000]
    mut_rate: [0.006]
    s_normal: [0.001, 0.004, 0.0004]
    s_range: [0.01]
  
  U_eff:
    pop_size: [5000]
    mut_rate_normal: [0.006, 0.02, 0.0001]
    mut_rate_range: [0.01]
    sel_coef: [0.001]

constants:
  CHRMLEN: 15000
  BURNIN: 25000
  N_SIM: 1000
  N_SAM: 500
  ESTIMATE_N_SIM: 200
  N_SIGMA: 100
  SIGMA_RANGE: [0.0, 1]
  N_SEL_COEF: 100
