executor: slurm
jobs: 20

# Global settings for every job
default-resources:
  slurm_partition: "pcmpg_el8"
  slurm_account: "yjauslin"
  threads: 1
  mem_mb: 1000
  runtime: 60
  slurm_extra: "'--mail-type=END --mail-user=yannick.jauslin@students.unibe.ch'"

# General Snakemake behavior
restart-times: 0
max-jobs-per-second: 5
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
rerun-incomplete: True